enum Topic {
  anarquismo,
  comunismo,
  conservadurismo,
  democraticoCristiano,
  ecologismo,
  fascismo,
  feminismo,
  liberalismo,
  libertarismo,
  marxismo,
  nacionalismo,
  neoliberalismo,
  progresismo,
  republicanismo,
  socialdemocracia,
  socialismo,
}
